import { poppins, manrope } from "./fonts";
import "./globals.css";
import "@/app/globalicons.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${manrope.variable}`}>{children}</body>
    </html>
  );
}
